[package]
name = "vrs-restaking-runtime-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
vrs-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
    "sp-runtime/std",
    "sp-api/std",
    "vrs-primitives/std",
]
