[package]
name = "vrs-nucleus-cage"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rocksdb = "0.21.0"
anyhow = "1"
log = "0.4"
env_logger = "0.10"
futures = { features = ["thread-pool"], version = "0.3.30" }
tokio = { version = "1", features = ["full"] }
hex = { version = "0.4" }
thiserror = "1"

vrs-runtime = { path = "../../runtime" }
vrs-metadata = { path = "../../metadata" }
vrs-primitives = { path = "../../primitives" }
vrs-nucleus-runtime-api = { path = "../../runtime-api/nucleus" }
vrs-validator-runtime-api = { path = "../../runtime-api/validator" }
vrs-nucleus-executor = { path = "../executor" }
vrs-nucleus-network = { path = "../network" }
vrs-tss = { path = "../../tss" }

codec = { workspace = true }
wasmtime = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sp-runtime = { workspace = true }
sc-network = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-keystore = { workspace = true }
sc-client-api = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true, default-features = false }
sc-transaction-pool = { workspace = true }
sc-authority-discovery = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-authority-discovery = { workspace = true }

[dev-dependencies]
temp-dir = "0.1.13"
