[package]
name = "vrs-a2a-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
codec = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
jsonrpsee = { features = ["server", "macros"], version = "0.23" }
async-trait  = { version = "0.1.81" }
log = "0.4"
a2a-rs = { path = "../../crates/a2a" }
vrs-primitives = { path = "../../primitives" }
vrs-a2a-runtime-api = { path = "../../runtime-api/a2a" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
