[package]
name = "nucleus-examples"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
nucleus-core = { path = "../nucleus-core" }
