[package]
name = "vrs-nucleus-examples"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
vrs-core-sdk = { path = "../core-sdk" }
codec = { workspace = true, default-features = false }
