[package]
name = "vrs-validator-runtime-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sp-api = { workspace = true, default-features = false }
# sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
codec = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
vrs-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "sp-core/std",
    "sp-api/std",
    "sp-std/std",
    "vrs-primitives/std",
]
