[package]
name = "vrs-mcp-runtime-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sp-api = { workspace = true, default-features = false }
vrs-primitives = { path = "../../primitives", default-features = false }
sp-std = { workspace = true, default-features = false }
pallet-mcp = { path = "../../pallets/mcp", default-features = false }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "pallet-mcp/std",
    "vrs-primitives/std",
    "sp-std/std",
]
