[package]
name = "vrs-gluon-relayer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
futures = { features = ["thread-pool"], version = "0.3.30" }
tokio = { version = "1", features = ["full"] }
hex = { version = "0.4" }
thiserror = "1"

vrs-runtime = { path = "../../runtime" }
vrs-metadata = { path = "../../metadata" }
vrs-primitives = { path = "../../primitives" }
vrs-nucleus-runtime-api = { path = "../../runtime-api/nucleus" }
vrs-validator-runtime-api = { path = "../../runtime-api/validator" }
vrs-nucleus-executor = { path = "../executor" }
vrs-nucleus-network = { path = "../network" }
codec = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sp-runtime = { workspace = true }
sc-network = { workspace = true }
sp-io = { workspace = true }
sp-core = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-keystore = { workspace = true }
sc-client-api = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
sc-authority-discovery = { workspace = true }
sp-authority-discovery = { workspace = true }
sc-network-types = { workspace = true }
