[package]
name = "vrs-swap-runtime-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
pallet-swap = { default-features = false, path = "../../swap" }
sp-api = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "pallet-swap/std",
    "sp-api/std",
    "sp-runtime/std",
]