name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl libprotobuf-dev protobuf-compiler

      - name: Install Rust toochain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: false
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, rust-src

      - name: Build
        run: cargo build --all-features --release --verbose

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        draft: true
        prerelease: true
        with:
          files: |
            target/release/verisense
            target/release/wbuild/vrs-runtime/vrs_runtime.compact.compressed.wasm
            spec/
            scripts/
            README.md
            LICENSE
