[package]
name = "vrs-nucleus-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
codec = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
vrs-core-sdk = { workspace = true }
sc-transaction-pool-api = "35.0.0"
sc-network = "0.42.0"
sc-network-types = "0.12.1"
jsonrpsee = { features = ["server", "macros"], version = "0.23" }
futures = { features = ["thread-pool"], version = "0.3.30" }
serde_json = { version = "1.0" }
async-trait  = { version = "0.1.81" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
hex = "0.4"
vrs-nucleus-executor = { path = "../../subnet/executor" }
vrs-primitives = { path = "../../primitives" }
vrs-nucleus-runtime-api = { path = "../../runtime-api/nucleus" }
vrs-gluon-relayer = { path = "../../subnet/relayer" }
